# Generated by Django 5.1.6 on 2025-02-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tablo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_u', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Уникальный идентификатор')),
                ('name', models.TextField(blank=True, default=None, null=True, verbose_name='Наименование')),
                ('name_eng', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='Наименование на английском')),
                ('abbreviation', models.TextField(blank=True, default=None, max_length=12, null=True, verbose_name='Аббревиатура')),
                ('oid_parameter', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='OID справочника с параметрами шкалы')),
                ('id_parameter', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Группировочный код шкалы в параметрах')),
                ('oid_intepretation', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='OID справочника с интерепритацией шкалы')),
                ('id_intepretation', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Группировочный код шкалы в интепритациях')),
                ('point_scale', models.TextField(blank=True, default=None, max_length=10, null=True, verbose_name='Признак балльной шкалы')),
                ('valid', models.CharField(blank=True, default=None, null=True, verbose_name='Валидация')),
                ('valid_author', models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name=' Названия и авторы')),
                ('valid_doi', models.TextField(blank=True, default=None, max_length=11, null=True, verbose_name='Идентификатор публикации')),
                ('org', models.TextField(blank=True, default=None, null=True, verbose_name='Организация')),
            ],
        ),
    ]
