# Generated by Django 5.1.6 on 2025-02-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablo',
            name='abbreviation',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='tablo',
            name='id_intepretation',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Группировочный код шкалы в интерпретациях'),
        ),
        migrations.AlterField(
            model_name='tablo',
            name='name_eng',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Наименование на английском'),
        ),
        migrations.AlterField(
            model_name='tablo',
            name='oid_intepretation',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='OID справочника с интерпретацией шкалы'),
        ),
        migrations.AlterField(
            model_name='tablo',
            name='point_scale',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Признак балльной шкалы'),
        ),
        migrations.AlterField(
            model_name='tablo',
            name='valid',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Валидация'),
        ),
        migrations.AlterField(
            model_name='tablo',
            name='valid_author',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Названия и авторы'),
        ),
        migrations.AlterField(
            model_name='tablo',
            name='valid_doi',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='Идентификатор публикации'),
        ),
    ]
